# Generated by Django 2.0.1 on 2018-01-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(default='imagem_livro/livro.png', upload_to='imagem_livro/'),
        ),
    ]
